SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS food_allergic;
DROP TABLE IF EXISTS allergic;
DROP TABLE IF EXISTS food;
DROP TABLE IF EXISTS tables;
DROP TABLE IF EXISTS payment_method;
DROP TABLE IF EXISTS guest;
DROP TABLE IF EXISTS order_food;
DROP TABLE IF EXISTS order_table;
DROP TABLE IF EXISTS orders;

CREATE TABLE food (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    image VARCHAR(255) NOT NULL
);

CREATE TABLE allergic (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    image VARCHAR(255) NOT NULL
);

CREATE TABLE food_allergic (
    food_id INTEGER NOT NULL,
    allergic_id INTEGER NOT NULL,
    PRIMARY KEY (food_id, allergic_id),
    FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE CASCADE,
    FOREIGN KEY (allergic_id) REFERENCES allergic (id) ON DELETE CASCADE
);

CREATE TABLE tables (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    number_of_seats INTEGER NOT NULL,
    occupied BOOLEAN NOT NULL
);

CREATE TABLE payment_method (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL
);

CREATE TABLE orders (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    payment_method VARCHAR(255) NOT NULL,
    total INTEGER NOT NULL,
    prepared TINYINT(1) NOT NULL
);

CREATE TABLE order_food (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    order_id INTEGER NOT NULL,
    food_name VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE TABLE order_table (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    order_id INTEGER NOT NULL,
    table_id INTEGER NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

SET FOREIGN_KEY_CHECKS = 1;